FROM mysql:8.0
EXPOSE 3306
COPY ./Migrations/docker-migrations/cerate/ /home/database/
COPY ./Migrations/docker-migrations/dataset/ /home/database/
COPY ./Migrations/docker-migrations/init_database.sh /docker-entrypoint-initdb.d/init_database.sh
RUN chmod +x /docker-entrypoint-initdb.d/init_database.sh