#stage 1
FROM node:21-slim as node
WORKDIR /app
COPY . .
RUN npm install -g npm@latest
RUN npm install
RUN npm run build:dev

#stage 2
FROM nginx:alpine
COPY --from=node /app/dist/despesas-frontend-angular /usr/share/nginx/html
COPY nginx.dev.conf /etc/nginx/conf.d/default.conf
EXPOSE 4200
CMD ["nginx", "-g", "daemon off;"]
