version: '3.4'
services:
  despesas-frontend-angular-prod:
    container_name: prod
    image: alexfariakof/despesas-frontend-angular-img
    build:
      context: .
      dockerfile: ./Dockerfile.production
    environment:
      NODE_ENV: production
    ports:
      - 80:80
      - 443:443
