version: '3.4'

services:
  despesas-frontend-angular-dev:
    container_name: dev
    image: alexfariakof/despesas-frontend-angular-dev-img
    build:
      context: .
      dockerfile: ./Dockerfile.development
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
