version: '3.9'

services:
  migrations.mysqlserver:
    domainname: migrations
    container_name: maria-server-in-docker
    image: mariadb:10.3.39
    restart: always
    environment:
        TZ: America/Sao_Paulo
        MARIADB_ROOT_PASSWORD: "!12345"
        MARIADB_USER: docker
        MARIADB_PASSWORD: docker
        MARIADB_DATABASE: DespesasPessoaisDB
        LANG: C.UTF-8
    ports:
        - "3306:3306"
    volumes:
        - mariadb_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci


volumes:
  mariadb_data:
