FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

EXPOSE 42536
ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://+:42536

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["despesas-backend-api-net-core/despesas-backend-api-net-core.csproj", "."]
RUN dotnet restore "despesas-backend-api-net-core.csproj"
COPY . .
RUN rm --force ./despesas-backend-api-net-core/appsettings.json
RUN rm --force ./despesas-backend-api-net-core/appsettings.development.json
RUN mv ./despesas-backend-api-net-core/appsettings.docker.json ./despesas-backend-api-net-core/appsettings.json
RUN rm --force ./despesas-backend-api-net-core/appsettings.docker.json

WORKDIR "/src/."
RUN dotnet build "despesas-backend-api-net-core/despesas-backend-api-net-core.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "despesas-backend-api-net-core/despesas-backend-api-net-core.csproj" -c Release -o /app/publish /p:UseAppHost=false


FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "despesas-backend-api-net-core.dll"]