FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

EXPOSE 42534
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:42534

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["despesas-backend-api-net-core/despesas-backend-api-net-core.csproj", "."]
RUN dotnet restore "despesas-backend-api-net-core.csproj"
COPY . .

WORKDIR "/src/."
RUN dotnet build "despesas-backend-api-net-core/despesas-backend-api-net-core.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "despesas-backend-api-net-core/despesas-backend-api-net-core.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "despesas-backend-api-net-core.dll"]

